name = "treasury"
main = "worker.js"
compatibility_date = "2026-05-03"
workers_dev = true
keep_vars = true

[vars]
OPENAI_MODEL = "gpt-5.4-mini"

[[kv_namespaces]]
binding = "TREASURY_KV"
id = "37710a93cc41472c9eee6d973e9f8ea2"

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"
